// --- AUTO-GENERATED BY sync_constants.js ---
// --- DO NOT EDIT MANUALY ---
// Source: phaser_server/src/config/ServerConstants.js

export const SHARED_CONFIG = {
    "WORLD_SIZE": 10000,
    "FPS": 60,
    "FOOD_RADIUS": 10,
    "BASE_SPEED": 3,
    "BOOST_SPEED": 6,
    "TURN_SPEED": 0.05,
    "PIXELS_PER_SEGMENT": 12,
    "INITIAL_LENGTH": 5,
    "HITBOX_SENSITIVITY": 1,
    "BASE_MAGNET_RADIUS": 80,
    "BOOST_COST_INTERVAL": 90,
    "MAX_PLAYER_SCALE": 1.2,
    "PLAYER_SCALE_BASE": 0.6,
    "PLAYER_SCALE_GROWTH": 0.005,
    "ITEMS": {
        "SPEED_UP": {
            "id": "speed",
            "price": 100,
            "duration": 10000,
            "cooldown": 10000,
            "buffValue": 4,
            "description": "Speed +4 (10s)"
        },
        "MAGNET": {
            "id": "magnet",
            "price": 200,
            "duration": 10000,
            "cooldown": 15000,
            "buffValue": 200,
            "description": "Magnet Radius 200 (10s)"
        },
        "GHOST": {
            "id": "ghost",
            "price": 300,
            "duration": 5000,
            "cooldown": 20000,
            "buffValue": 0,
            "description": "Ghost Mode (5s)"
        }
    }
};
