const fs = require('fs');
const path = require('path');

// 1. Definition of what to sync
const SHARED_KEYS = [
    'WORLD_SIZE',
    'FPS',
    'FOOD_RADIUS',
    'BASE_SPEED',
    'BOOST_SPEED',
    'TURN_SPEED',
    'PIXELS_PER_SEGMENT',
    'INITIAL_LENGTH',
    'HITBOX_SENSITIVITY',
    'BASE_MAGNET_RADIUS',
    'BOOST_COST_INTERVAL',
    'MAX_PLAYER_SCALE',
    'PLAYER_SCALE_BASE',
    'PLAYER_SCALE_GROWTH',
    'ITEMS'
];

// 2. Paths
const SERVER_CONSTANTS_PATH = path.join(__dirname, '../src/config/ServerConstants.js');
const CLIENT_SHARED_PATH = path.join(__dirname, '../../web/src/config/SharedConfig.js');

// 3. Read Server Constants
console.log('Reading Server Constants:', SERVER_CONSTANTS_PATH);
const serverConstants = require(SERVER_CONSTANTS_PATH);

// 4. Extract Shared Data
const sharedData = {};
SHARED_KEYS.forEach(key => {
    if (serverConstants[key] !== undefined) {
        sharedData[key] = serverConstants[key];
    } else {
        console.warn(`WARNING: Key ${key} not found in server constants!`);
    }
});

// 5. Format as ESM for Client
const fileContent = `// --- AUTO-GENERATED BY sync_constants.js ---
// --- DO NOT EDIT MANUALY ---
// Source: phaser_server/src/config/ServerConstants.js

export const SHARED_CONFIG = ${JSON.stringify(sharedData, null, 4)};
`;

// 6. Write to Client
console.log('Writing to Client:', CLIENT_SHARED_PATH);
fs.writeFileSync(CLIENT_SHARED_PATH, fileContent);

console.log('Sync Complete!');
